#+OPTIONS: TOC:nil DATE:nil AUTHOR:nil
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}

Assignment 1: Software Requirements Specification

Team: 6

Project Title: Flowchart Creator

Members:
1. Sam Messina
2. Taylor Flatt
3. Michael Easton
4. Reid Trevonian


| Stakeholders      | Requirements                                                                 |
|-------------------+------------------------------------------------------------------------------|
| Users/Client side |                                                                              |
|                   | FR1. Users can create new flowcharts.                                        |
|                   | FR2. Users can delete existing flowcharts.                                   |
|                   | FR3. Users can add steps to an existing flowchart.                           |
|                   | FR4. Users can edit steps in an existing flowchart.                          |
|                   | FR5. Users can remove a step from an existing flowchart.                     |
|                   | FR6. Users can modify a step in a flowchart.                                 |
|                   | FR6. Users can drag and drop steps to new locations in a flowchart.          |
|                   | FR8. Users can use conditional statments in flowcharts.                      |
|                   | FR9. Users can use conditional loops in their flowcharts.                    |
|                   | FR13. Users can access saved copies of flowcharts while logged in.           |
|                   | FR18. users can save flowcharts in different view styles by                  |
|                   | \hspace{5em} choosing from a list of templates                               |
|                   | FR19. Interface allows for keyboard shortcuts                                |
|                   | NFR5. Errors should not include relevant security information                |
|                   | NFR6. keyboard commands allow user to save                                   |
|                   | NFR8. Editor displays changes immediately                                    |
| Server side       |                                                                              |
|                   | FR7. Users can export to XML/JSON formats.                                   |
|                   | FR10. Users can create a personal account.                                   |
|                   | FR11. Users can log in to their account.                                     |
|                   | FR12. Users can freely delete their account.                                 |
|                   | FR14. Flowcharts can be shared between multiple accounts.                    |
|                   | FR15. users can publish completed charts via publicly-accessible URL         |
|                   | FR15. Users can recover forgotten passwords via email                        |
|                   | FR17. users can save charts as private, preventing them from                 |
|                   | \hspace{5em} being viewed or edited by other users                           |
|                   | NFR1. User passwords are securely stored with ISO/IEC 27034-1:2011           |
|                   | NFR2. Server should be publicly accessible                                   |
|                   | NFR3. Must be 100% operational with 99% uptime                               |
|                   | NFR4. all user input is validated                                            |
|                   | NFR7. any new flowcharts or changes to existing flowcharts are               |
|                   | \hspace{5em} saved as non-public drafts until published                      |
|                   | NFR9. When a user deletes their account, all associated data is also removed |


------
SAM
------

FR3. Users can add steps to an existing flowchart.

Description: 
Steps can be added to the flowchart, and include a title, description, and type. Steps may be of conditional, loop, terminal, or non-terminal types.


FR4. Users can edit steps in an existing flowchart.

Description: 
Once a step is created, it may be edited. Users can change the type, description, or title of the step at any time.


FR6. Users can drag and drop steps to new locations in a flowchart.

Description: 
Steps can be moved after creation by dragging them to a new location. Further prompts may be necessary, depending on the type of step being moved.


FR7. Users can export to XML/JSON formats.

Description: 
Users will be able to export their flowchart in a portable, flat document format. The exact format will be decided on during development.

FR8. Users can use conditional statments in flowcharts.

Description: 
All major flowchart features will be available. Conditional statements allow a step to have >1 options following it. Based on a given condition, users will be able to branch the flowchart into different options.

------
REID
------

FR9. Users can use conditional loops in their flowcharts.

Description: 


FR10. Users can create a personal account.

Description: 


FR12. Users can freely delete their account.

Description: 


FR14. Flowcharts can be shared between multiple accounts.

Description: 

FR15. users can publish completed charts via publicly-accessible URL

Description: 

------
TAYLOR
------

FR15. Users can recover forgotten passwords via email

Description: Through the web-interface, authenticated users can send a reset password link to their email if their account already exists from a reset passwords link. This will allow the user to reset their password if forgotten to a different password. The user must have access to the email account that they used to create their account.


FR17. users can save charts as private, preventing them from being viewed or edited by other users

Description: Through the flowchart interface, authenticated users can save their charts as private allowing no one but themselves to view or edit the flowchart. This option is not permanent and a user can set their flowchart to private or public at any time.


FR13. Users can access saved copies of flowcharts while logged in.

Description: Through the flowchart interface, authenticated users can open previously created flowcharts allowing them to edit the contents or options of the flowchart. Any changes made to existing flowcharts will overwrite those flowcharts.


FR18. users can save flowcharts in different view styles by choosing from a list of templates

Description: Through the flowchart interface, authenticated users can apply different visual templates to their flowchart changing the style. This cosmetic option can be changed as many times as the user would like. This option should only change the way in which the content is displayed, not the content itself.


FR19. Interface allows for keyboard shortcuts

Description: Through the web-interface, authenticated users can use keyboard shortcuts to perform different actions such as saving and exporting. These actions should override any pre-existing keyboard shortcut that may exist within the browser.

------
MICHAEL
------

NFR4. all user input is validated

Description: 


NFR5. Errors should not include relevant security information

Description: 


NFR7. any new flowcharts or changes to existing flowcharts are saved as non-public drafts until published

Description: 


NFR8. Editor displays changes immediately

Description: 


NFR9. When a user deletes their account, all associated data is also removed

Description: 

